// DiffusionHeightSource.h — the STREAMING IHeightSource for infinite AI terrain (Phase 2).
//
// WHAT THIS IS (plain English):
// Every voxel column asks one question — "how high is the ground at world column (wx,wz)?"
// Phase 1 answered it from ONE bounded image (mira::ImageHeightmap). That can't cover an
// infinite world. This class answers the same question from a CACHE OF STREAM TILES owned
// by FDiffusionDemService: it finds the tile that covers the column, reads that tile's
// coarse DEM, and runs the SAME detail bridge (mira::tdiff::sample_height_voxels) the
// bounded path uses — so a column generated by streaming looks identical to one the bounded
// image produced for the same coarse data (design risk R9: no Phase-1/Phase-2 seam).
//
// THREADING (read this — it is the whole safety story):
//   * height_voxels_at() / sample_value() run on COLUMN WORKER threads and are strictly
//     READ-ONLY. They do an array read + arithmetic. They NEVER build a tile, never run
//     inference, never allocate on the heap on the hot path (a reused thread-local scratch
//     buffer holds the per-tile voxel conversion), and never block.
//   * Tiles are made resident on the GAME THREAD via FDiffusionDemService::EnsureTileResident
//     BEFORE the column job is enqueued. By the time a worker samples here, the covering
//     tile (and its 8-neighbour ring, which the bicubic + slope stencil can reach into) is
//     guaranteed resident. If a tile is somehow missing, this NEVER invents a hole/NaN — it
//     degrades to a flat clamped base height.
//
// HOW AVoxelWorld WILL HOLD + DRIVE THIS (wire-in note for the integration step — NOT done
// here; do NOT edit VoxelWorld.* or TdiffWorldHook.* for this):
//   1. The world owns ONE FDiffusionDemService and ONE mira::DiffusionHeightSource (held by
//      value/unique_ptr next to the existing DiffusionHeightmap), constructed with the
//      service*, the world seed, the SAME DetailBridgeParams the bounded path uses (see the
//      CRITICAL note below), Svc->GetVerticalScaleVoxels()/GetVerticalBaseVoxels(), and
//      Svc->TileSpanVoxels.
//   2. Each AVoxelWorld::TickStreaming, on the GAME THREAD, for every column the streamer
//      wants this tick: compute tile = FDiffusionDemService::TileCoordOf(wx, wz, TileSpan);
//      call Svc->SetTileFocus(tile); call Svc->EnsureTileResident(seed, tile) for that tile
//      AND its 8-neighbour ring. If any returns nullptr, DEFER that column (do not enqueue);
//      otherwise EnqueueColumnGen as usual.
//   3. Install this object as the generator's height source (set_height_source(&Source) via
//      SnapshotGenParams/BuildGen), exactly where DiffusionHeightmap is installed today.
//   4. On ClearWorld / reseed, call Svc->ClearTiles() (alongside ClearCache()).
//
// CRITICAL (risk R9): for streaming output to match the bounded BuildHeightmapFromCoarse,
// the DetailBridgeParams passed to the ctor MUST be the SAME ones that path uses — including
// its AI-path overrides (slopeBoost=0.25, detailAmpVoxels=12.0, detailFreq=0.02). The seed
// field is fixed by this ctor to `Seed` automatically (mirroring DiffusionDemService.cpp's
// `Params.seed = Seed`), so the caller need not set it. The metres->voxel conversion + 8192
// clamp are reused verbatim (see the .cpp), keyed off the same VerticalScale/Base + the
// shared FDiffusionDemService::kMaxSurfaceVoxels constant.
//
// This module (MiraThalTerrainAI) depends on MiraThalVoxel, so it can see IHeightSource.h +
// DetailBridge.h; MiraThalVoxel never references this class (one-way dependency intact).

#pragma once

#include "CoreMinimal.h"
#include "Core/IHeightSource.h"        // mira::IHeightSource — the interface we implement
#include "Core/Tdiff/DetailBridge.h"   // mira::tdiff::DetailBridgeParams + sample_height_voxels

// Forward-declare the resident-tile owner; the .cpp includes the full header. Non-owning:
// the service outlives this source (mirrors set_height_source's "caller keeps it alive").
class FDiffusionDemService;
struct FCoarseDem;

namespace mira {

// =============================================================================
// DiffusionHeightSource — a streaming IHeightSource backed by a resident tile cache.
// =============================================================================
class DiffusionHeightSource final : public IHeightSource
{
public:
	// Svc                  resident-tile owner (NON-OWNING — must outlive this source).
	// Seed                 world seed (selects the tiles + fixes the detail field).
	// Detail               detail-bridge knobs; MUST match the bounded path's params
	//                      (see the CRITICAL note above). Its `seed` is overwritten with Seed.
	// VerticalScaleVoxels  normalised-cell -> voxel-height scale (use Svc->GetVerticalScaleVoxels()).
	// VerticalBaseVoxels   normalised-cell -> voxel-height base  (use Svc->GetVerticalBaseVoxels()).
	// TileSpanVoxels       tile size on the world grid (use Svc->TileSpanVoxels).
	DiffusionHeightSource(const FDiffusionDemService* InSvc, int64 InSeed,
	                      mira::tdiff::DetailBridgeParams InDetail,
	                      double InVerticalScaleVoxels, double InVerticalBaseVoxels,
	                      int32 InTileSpanVoxels);

	// --- IHeightSource ---------------------------------------------------------
	// Ready to be sampled at all? True once the service is set (the per-tile residency
	// guarantee is enforced upstream on the game thread, not here).
	bool valid() const override;

	// Continuous (pre-floor) ground height in voxels at a world column. WORKER, read-only.
	float sample_value(double world_x, double world_z) const override;

	// Integer ground voxel-Y = floor(continuous height). The only method compute_ground_y
	// calls. WORKER, read-only.
	int height_voxels_at(int world_x, int world_z) const override;

private:
	// Shared core: continuous voxel height at an integer world column (both public methods
	// funnel through this). Returns a safe clamped base height if the covering tile is not
	// resident (never a hole/NaN).
	double SampleContinuous(int WorldX, int WorldZ) const;

	const FDiffusionDemService*     Svc = nullptr; // non-owning resident-tile lookup
	int64                           Seed = 0;
	mira::tdiff::DetailBridgeParams Detail;        // seed fixed to Seed in the ctor
	double                          VerticalScaleVoxels = 7000.0;
	double                          VerticalBaseVoxels  = 120.0;
	int32                           TileSpanVoxels = 19200;
};

} // namespace mira
