class_name EntityRecord
extends Resource
# EntityRecord — POD snapshot of one persistent entity.
#
# The "state of the world" the player has interacted with — every persistent
# NPC, enemy, dropped item, etc. — lives as a list of these. The
# EntityRegistry indexes them by chunk; the EntityStreamer loads and frees
# them as the player moves around.
#
# Design choice — `state` is an opaque Dictionary so each entity type can
# stuff whatever it needs (Goblin: health + AI state; VoxelDrop: item_id +
# quantity; NPC: npc_id + schedule progress) without this base type
# growing per-type fields. Entities round-trip via `to_entity_record()` /
# `from_entity_record()` methods on the scene root.
#
# Reference: design/ENTITY_STREAMING.md (to be written) +
#            scripts/EntityStreamer.gd + scripts/EntityRegistry.gd.

# Unique entity ID — generated by EntityRegistry on first register if empty.
@export var entity_id: String = ""

# Path to the PackedScene used to instance this entity. Validated on load —
# if missing, the registry logs a warning and skips that entity.
@export var scene_path: String = ""

# World position + yaw. Pitch/roll are usually 0 for upright entities
# (NPCs, enemies). Drops and physics objects that need full rotation can
# stash extra orientation data in `state` if it matters.
@export var position: Vector3 = Vector3.ZERO
@export var rotation_y: float = 0.0

# Type-specific blob. Goblin: {"health": int, "ai_state": int}.
# VoxelDrop: {"item_id": String, "quantity": int}.
# NPC: {"npc_id": String, "schedule_index": int}.
@export var state: Dictionary = {}

# AI sleep tier — EntityStreamer drives this each tick based on player
# distance. Defaults to ACTIVE so a freshly-spawned entity reads as live.
@export var ai_tier: int = 0  # AITier.ACTIVE


# Convert to a plain-Dictionary (JSON-safe) representation. Used by
# EntityRegistry save_to_disk. Vector3 → [x, y, z]; nested Dictionary is
# stored as-is and must itself be JSON-safe (entity authors are
# responsible for not stuffing Resources / Objects into `state`).
func to_dict() -> Dictionary:
	return {
		"entity_id": entity_id,
		"scene_path": scene_path,
		"pos": [position.x, position.y, position.z],
		"rot_y": rotation_y,
		"state": state,
		"ai_tier": ai_tier,
	}


# Reverse of to_dict. Robust against missing keys (returns reasonable
# defaults) so an EntityRecord saved with an older schema still loads.
static func from_dict(d: Dictionary) -> EntityRecord:
	var r := EntityRecord.new()
	r.entity_id = String(d.get("entity_id", ""))
	r.scene_path = String(d.get("scene_path", ""))
	var p: Array = d.get("pos", [0.0, 0.0, 0.0])
	if p.size() >= 3:
		r.position = Vector3(float(p[0]), float(p[1]), float(p[2]))
	r.rotation_y = float(d.get("rot_y", 0.0))
	var s: Variant = d.get("state", {})
	if s is Dictionary:
		r.state = s
	r.ai_tier = int(d.get("ai_tier", 0))
	return r
