#!/usr/bin/env python3
"""rng_reference.py - pure-Python golden generator for the PortableRng C++ port.

Faithful re-implementation of terrain_diffusion/inference/portable_rng.py (the numba kernels),
with NO numba/numpy dependency, so it runs on a bare Python 3. Emits golden_rng.inc (a C++
include) holding, per seed: the first K raw PCG64 uint32 outputs, the first K standard-normal
values as their float32 bit patterns, and next_seed(seed). test_tdiff_rng.cpp compares the C++
PortableRng output against these for bit-exactness (Gate 2).

Run:  python rng_reference.py   (writes golden_rng.inc next to this file)
"""
import math
import struct
from pathlib import Path

MASK64 = 0xFFFFFFFFFFFFFFFF
MULT = 6364136223846793005
INC = 1442695040888963407
K = 16  # how many values per seed to capture
SEEDS = [1, 2, 42, 123456789, 0xDEADBEEF, 0x0123456789ABCDEF]


def pcg64_next(state):
    state = (state * MULT + INC) & MASK64
    x = (((state >> 18) ^ state) >> 27) & 0xFFFFFFFF
    rot = (state >> 59) & 31
    out32 = ((x >> rot) | (x << ((32 - rot) & 31))) & 0xFFFFFFFF
    return state, out32


def next_seed(seed):
    state = seed & MASK64
    state, lo = pcg64_next(state)
    state, hi = pcg64_next(state)
    return ((hi << 32) | lo) & MASK64


def raw_stream(seed, n):
    state = seed & MASK64
    out = []
    for _ in range(n):
        state, o = pcg64_next(state)
        out.append(o)
    return out


def normals(seed, n):
    state = seed & MASK64
    out = []
    inv = 1.0 / 4294967296.0
    while len(out) < n:
        state, u1 = pcg64_next(state)
        state, u2 = pcg64_next(state)
        v1 = 2.0 * (float(u1) + 1.0) * inv - 1.0
        v2 = 2.0 * (float(u2) + 1.0) * inv - 1.0
        s = v1 * v1 + v2 * v2
        if 0.0 < s < 1.0:
            f = math.sqrt(-2.0 * math.log(s) / s)
            out.append(v1 * f)
            if len(out) < n:
                out.append(v2 * f)
    return out[:n]


def f32_bits(x):
    """Round a Python float to float32 and return its IEEE-754 bit pattern as uint32."""
    return struct.unpack("<I", struct.pack("<f", x))[0]


def main():
    lines = []
    lines.append("// AUTO-GENERATED by rng_reference.py - DO NOT EDIT.")
    lines.append("// Golden PCG64 + Marsaglia-polar values from the repo's portable_rng algorithm.")
    lines.append("#pragma once")
    lines.append("#include <cstdint>")
    lines.append(f"static const int kGoldenK = {K};")
    lines.append("struct GoldenRng { uint64_t seed; uint32_t raw[%d]; uint32_t normbits[%d]; uint64_t next_seed; };" % (K, K))
    lines.append("static const GoldenRng kGoldenRng[] = {")
    for sd in SEEDS:
        raw = raw_stream(sd, K)
        nb = [f32_bits(v) for v in normals(sd, K)]
        ns = next_seed(sd)
        raw_s = ", ".join(f"{v}u" for v in raw)
        nb_s = ", ".join(f"{v}u" for v in nb)
        lines.append(f"  {{ {sd}ULL, {{ {raw_s} }}, {{ {nb_s} }}, {ns}ULL }},")
    lines.append("};")
    lines.append(f"static const int kGoldenRngCount = {len(SEEDS)};")
    out_path = Path(__file__).with_name("golden_rng.inc")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path} ({len(SEEDS)} seeds x {K} values)")


if __name__ == "__main__":
    main()
