#!/usr/bin/env python3
"""sched_reference.py - golden generator for the EdmDpmScheduler C++ port.

Unlike rng_reference.py (which re-implements the algorithm in pure Python), this
imports the REAL scheduler from the terrain-diffusion repo so the golden is the
genuine reference output:

    from terrain_diffusion.scheduler.dpmsolver import EDMDPMSolverMultistepScheduler

It instantiates the EXACT config world_pipeline.py uses
(sigma_min=0.002, sigma_max=80, sigma_data=0.5, + class defaults), and for a few
inference-step counts dumps:
  * the sigma schedule (n+1 values) and timestep schedule (n values), and
  * a synthetic denoise trajectory: starting from a fixed deterministic sample,
    feeding a deterministic fake model_output = 0.1*sample - 0.05*sigma at each
    step, calling scheduler.step(), and recording per-step summary stats plus the
    first few exact elements of prev_sample.

Emits sched_golden.inc (a C++ include, mirroring golden_rng.inc's structure) that
test_tdiff_scheduler.cpp compares against.

Run (from tests/standalone):
    set PYTHONPATH=D:\terrain-diffusion
    D:\terrain-diffusion\.venv\Scripts\python.exe tdiff\sched_reference.py
"""
import math
import struct
from pathlib import Path

import torch

from terrain_diffusion.scheduler.dpmsolver import EDMDPMSolverMultistepScheduler

# ---- frozen config: exactly what world_pipeline.py constructs -----------------
SIGMA_MIN = 0.002
SIGMA_MAX = 80.0
SIGMA_DATA = 0.5

# inference-step counts to capture
NS = [8, 16, 32]

# synthetic tensor element count (must match test_tdiff_scheduler.cpp)
COUNT = 16

# how many exact elements per trajectory checkpoint (must match the C++ TrajPoint)
NEXACT = 4


def make_scheduler():
    # class defaults give us: solver_order=2, algorithm_type="dpmsolver++",
    # solver_type="midpoint", sigma_schedule="karras", prediction_type="epsilon",
    # rho=7.0, final_sigmas_type="zero", lower_order_final=True, scaling_p=None.
    return EDMDPMSolverMultistepScheduler(
        sigma_min=SIGMA_MIN, sigma_max=SIGMA_MAX, sigma_data=SIGMA_DATA
    )


def initial_sample(count):
    """Deterministic fixed starting sample. MUST match the C++ test formula."""
    s = torch.empty(count, dtype=torch.float32)
    for j in range(count):
        s[j] = 0.5 * math.sin(0.3 * j) - 0.2 * math.cos(0.11 * j) + 0.01 * j
    return s


def denoise_trajectory(n):
    """Run the synthetic denoise for n steps; return list of per-step checkpoints.

    Each checkpoint: (e0..e{NEXACT-1}, mean, min, max, l2norm) computed in float64
    over the float32 prev_sample.
    """
    sched = make_scheduler()
    sched.set_timesteps(n)

    sample = initial_sample(COUNT)
    traj = []
    for i in range(n):
        sigma = float(sched.sigmas[i])
        # deterministic fake model output: closed form of (sample, sigma)
        model_output = 0.1 * sample - 0.05 * sigma
        prev = sched.step(model_output, sched.timesteps[i], sample, return_dict=False)[0]
        sample = prev

        arr = prev.to(torch.float64)
        exact = [float(arr[k]) for k in range(NEXACT)]
        mean = float(arr.mean())
        mn = float(arr.min())
        mx = float(arr.max())
        norm = float(torch.sqrt((arr * arr).sum()))
        traj.append((exact, mean, mn, mx, norm))
    return traj


def fmt_double(x):
    # full-precision round-trippable double literal
    if math.isinf(x):
        return "(1.0/0.0)" if x > 0 else "(-1.0/0.0)"
    if math.isnan(x):
        return "(0.0/0.0)"
    return repr(float(x))


def main():
    lines = []
    lines.append("// AUTO-GENERATED by sched_reference.py - DO NOT EDIT.")
    lines.append("// Golden schedule + synthetic-denoise trajectory from the REAL")
    lines.append("// terrain_diffusion EDMDPMSolverMultistepScheduler.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("struct TrajPoint {")
    lines.append("    double e[%d];" % NEXACT)
    lines.append("    double mean, mn, mx, norm;")
    lines.append("};")
    lines.append("struct SchedGolden {")
    lines.append("    int n;")
    lines.append("    const double* sigmas;    // n+1")
    lines.append("    const double* timesteps; // n")
    lines.append("    const TrajPoint* traj;   // n")
    lines.append("};")
    lines.append("static const int kSchedCount = %d;  // tensor element count" % COUNT)
    lines.append("static const int kSchedNExact = %d;" % NEXACT)
    lines.append("")

    table = []
    for n in NS:
        sched = make_scheduler()
        sched.set_timesteps(n)
        sigmas = [float(v) for v in sched.sigmas.tolist()]      # n+1
        timesteps = [float(v) for v in sched.timesteps.tolist()]  # n
        traj = denoise_trajectory(n)

        sig_s = ", ".join(fmt_double(v) for v in sigmas)
        ts_s = ", ".join(fmt_double(v) for v in timesteps)
        lines.append("static const double kSigmas_%d[] = { %s };" % (n, sig_s))
        lines.append("static const double kTimesteps_%d[] = { %s };" % (n, ts_s))
        lines.append("static const TrajPoint kTraj_%d[] = {" % n)
        for (exact, mean, mn, mx, norm) in traj:
            ex_s = ", ".join(fmt_double(v) for v in exact)
            lines.append("    { { %s }, %s, %s, %s, %s }," % (
                ex_s, fmt_double(mean), fmt_double(mn), fmt_double(mx), fmt_double(norm)))
        lines.append("};")
        table.append("    { %d, kSigmas_%d, kTimesteps_%d, kTraj_%d }," % (n, n, n, n))
        lines.append("")

    lines.append("static const SchedGolden kSchedGolden[] = {")
    lines.extend(table)
    lines.append("};")
    lines.append("static const int kSchedGoldenCount = %d;" % len(NS))

    out_path = Path(__file__).with_name("sched_golden.inc")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote %s (%d schedules, count=%d)" % (out_path, len(NS), COUNT))


if __name__ == "__main__":
    main()
