#!/usr/bin/env python3
"""synthmap_reference.py - golden generator for the SyntheticMap C++ port.

Calls the REAL terrain-diffusion synthetic_map.py (make_synthetic_map_factory) for a
fixed seed + stats + set of regions, and dumps the resulting conditioning channels to
synthmap_golden.inc (a C++ include). test_tdiff_synthmap.cpp compares the C++
mira::tdiff::SyntheticMap output against these goldens (parity gate).

This is the ONLY place the real Python pipeline runs; the C++ side never imports Python.

Run (from this directory) with the terrain-diffusion venv + repo on PYTHONPATH:
  PYTHONPATH=D:/terrain-diffusion \
    D:/terrain-diffusion/.venv/Scripts/python.exe synthmap_reference.py

It writes synthmap_golden.inc next to this file. The stats JSON it loads is the same
copy the C++ test loads, so both sides histogram-match against identical tables.
"""
import os
import struct
import numpy as np

import terrain_diffusion.inference.synthetic_map as sm

# --- Fixed inputs (must match test_tdiff_synthmap.cpp) -----------------------
SEED = 12345
STATS_PATH = r"D:\terrain-diffusion\trace_singletile\synthetic_map_stats.json"

# Regions to sample: (i1, j1, i2, j2). One square at origin, one offset square,
# one offset NON-square (exercises the meshgrid/flatten/reshape index mapping).
REGIONS = [
    (0, 0, 24, 24),
    (37, 91, 61, 115),
    (5, 10, 21, 30),  # W=16, H=20 (non-square)
]

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "synthmap_golden.inc")


def f32(x):
    """Round-trip through float32 so emitted literals are exact float32 values."""
    return float(np.float32(x))


def main():
    # Point the factory's stats cache at our committed copy so it LOADS (never recomputes).
    sm.STATS_CACHE_PATH = STATS_PATH
    assert os.path.exists(STATS_PATH), f"stats not found: {STATS_PATH}"

    # The same seed-derivation the C++ port mirrors.
    actual_seeds = [((SEED) + i + 1) & 0x7FFFFFFF for i in range(5)]

    factory = sm.make_synthetic_map_factory(seed=SEED)

    lines = []
    lines.append("// AUTO-GENERATED by synthmap_reference.py - DO NOT EDIT.")
    lines.append("// Golden synthetic-map conditioning from the real terrain-diffusion pipeline.")
    lines.append("#pragma once")
    lines.append("#include <cstdint>")
    lines.append(f"static const int kSynthSeed = {SEED};")
    lines.append("static const int kSynthActualSeeds[5] = { " +
                 ", ".join(str(s) for s in actual_seeds) + " };")
    lines.append(f"static const int kSynthRegionCount = {len(REGIONS)};")

    # Region bounds table.
    lines.append("struct SynthRegion { int i1, j1, i2, j2, n; };")
    region_entries = []
    for (i1, j1, i2, j2) in REGIONS:
        n = (i2 - i1) * (j2 - j1)
        region_entries.append(f"  {{ {i1}, {j1}, {i2}, {j2}, {n} }}")
    lines.append("static const SynthRegion kSynthRegions[] = {\n" +
                 ",\n".join(region_entries) + "\n};")

    # For each region: full 5-channel map (finalize + sqrt on elev) and raw stack,
    # each channel flattened (numpy C-order). Stored as float32 literals.
    def emit_block(name, arr5):
        # arr5: shape (5, H, W) numpy. Flatten each channel C-order.
        flat = [np.asarray(arr5[c], dtype=np.float32).flatten() for c in range(5)]
        n = flat[0].shape[0]
        chunks = []
        for c in range(5):
            vals = ", ".join(repr(f32(v)) + "f" for v in flat[c])
            chunks.append(f"  {{ {vals} }}")
        lines.append(f"static const float {name}[5][{n}] = {{\n" +
                     ",\n".join(chunks) + "\n};")

    for idx, (i1, j1, i2, j2) in enumerate(REGIONS):
        # NOTE on argument order: world_pipeline calls the factory with swapped
        # coords, but here we test the factory's own native (i1,j1,i2,j2) contract,
        # which is what SyntheticMap.h mirrors directly. sample_full and .sample_raw
        # take (i1, j1, i2, j2).
        full = factory(i1, j1, i2, j2).numpy()           # (5, H, W) float32
        raw = np.asarray(factory.sample_raw(i1, j1, i2, j2), dtype=np.float32)
        emit_block(f"kSynthFull_{idx}", full)
        emit_block(f"kSynthRaw_{idx}", raw)

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(REGIONS)} regions, seed {SEED})")
    print(f"actual_seeds = {actual_seeds}")


if __name__ == "__main__":
    main()
