#!/usr/bin/env python3
"""window_reference.py - pure-Python golden generator for the WeightWindow C++ port.

Faithful re-implementation of terrain_diffusion/inference/world_pipeline.py
linear_weight_window(size, device, dtype), with NO numpy/torch/external dependency.
All arithmetic uses Python's native float (IEEE-754 float64), then each value is
truncated to float32 via struct.pack exactly as C++ static_cast<float>(double_val)
does - so the golden and the C++ output are bit-for-bit identical.

Emits window_golden.inc (a C++ header include) containing, for each captured size,
the size*size values as IEEE-754 uint32 bit patterns. test_tdiff_window.cpp compares
the C++ WeightWindow.h output against these.

Run:  python tdiff/window_reference.py   (writes window_golden.inc next to this file)
"""
import struct
from pathlib import Path

# Sizes to capture golden for. 8 and 16 are typical diffusion tile sizes;
# 4 is added as a tiny smoke-check where every value is easy to hand-verify.
SIZES = [4, 8, 16]
EPS = 1e-3


def linear_weight_window(size: int):
    """Return a list of size*size Python floats (float64), row-major.

    Mirrors C++ WeightWindow.h exactly:
      mid = (size - 1) / 2.0
      one_minus_eps = 1.0 - eps
      for each (y, x):
        ratio_y = clamp(|y - mid| / mid, 0, 1)
        wy = 1 - one_minus_eps * ratio_y
        ratio_x = clamp(|x - mid| / mid, 0, 1)
        wx = 1 - one_minus_eps * ratio_x
        out[y*size + x] = wy * wx  (float64, later packed to float32)
    """
    s = size
    mid = (s - 1) / 2.0          # float64, matches C++ double
    one_minus_eps = 1.0 - EPS    # == 0.999

    result = []
    for y in range(s):
        if mid == 0.0:
            # size == 1 degenerate case - full weight, no blending needed.
            wy = 1.0
        else:
            ratio = abs(y - mid) / mid
            ratio = max(0.0, min(1.0, ratio))   # clamp [0, 1]
            wy = 1.0 - one_minus_eps * ratio

        for x in range(s):
            if mid == 0.0:
                wx = 1.0
            else:
                ratio = abs(x - mid) / mid
                ratio = max(0.0, min(1.0, ratio))
                wx = 1.0 - one_minus_eps * ratio

            # Product in float64, to be packed as float32 (matching static_cast<float>).
            result.append(wy * wx)

    return result


def f32_bits(x: float) -> int:
    """Truncate a Python float to float32 and return its IEEE-754 bit pattern as uint32.

    Identical to the approach in rng_reference.py (the established template).
    struct.pack('<f', x) uses round-to-nearest-even, same as C++ static_cast<float>.
    """
    return struct.unpack("<I", struct.pack("<f", x))[0]


def main():
    lines = []
    lines.append("// AUTO-GENERATED by window_reference.py - DO NOT EDIT.")
    lines.append("// Golden linear_weight_window values from the terrain-diffusion port.")
    lines.append("// Regenerate: python tdiff/window_reference.py")
    lines.append("#pragma once")
    lines.append("#include <cstdint>")
    lines.append("")

    array_entries = []   # (size, array_name) for the lookup table at the end

    for sz in SIZES:
        vals   = linear_weight_window(sz)
        bits   = [f32_bits(v) for v in vals]
        name   = f"kWindowBits{sz}"
        count  = sz * sz

        array_entries.append((sz, name))

        lines.append(f"// size={sz}: {count} values in row-major order [y*{sz}+x].")
        lines.append(f"static const int kWindowSize{sz} = {sz};")
        lines.append(f"static const uint32_t {name}[{count}] = {{")

        # Emit one row per source grid row so the .inc is readable.
        row_strs = []
        for r in range(sz):
            row_bits = bits[r * sz : (r + 1) * sz]
            cells    = ", ".join(f"{b}u" for b in row_bits)
            row_strs.append(f"    /* row {r:2d} */ {cells}")

        lines.append(",\n".join(row_strs))
        lines.append("};")
        lines.append("")

    # Lookup table so test_tdiff_window.cpp can iterate over all sizes generically.
    lines.append("struct GoldenWindow { int size; const uint32_t* bits; };")
    init_list = ", ".join(f"{{ {sz}, {name} }}" for sz, name in array_entries)
    lines.append(f"static const GoldenWindow kGoldenWindows[] = {{ {init_list} }};")
    lines.append(f"static const int kGoldenWindowCount = {len(SIZES)};")
    lines.append("")

    out_path = Path(__file__).with_name("window_golden.inc")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path} ({len(SIZES)} window(s): sizes {SIZES})")


if __name__ == "__main__":
    main()
