# BarkManager.gd
# Autoload singleton. Manages bark line pools and the bark text overlay.
#
# REGISTER AS AUTOLOAD:
#   Project Settings → Autoload → add BarkManager.gd with node name "BarkManager"
#
# HOW IT WORKS:
#   1. On startup, loads bark line pools from /dialogue/scripts/barks/.
#      Each NPC has a .txt file per bark category (combat, exploration, etc.).
#      The file format is defined in design/BARK_LIBRARY.md.
#   2. When NPC.fire_bark() is called, BarkManager picks a random variant line
#      from that NPC's pool for the given trigger.
#   3. The line is shown as a temporary text overlay (portrait + text, corner of screen).
#      If the line has been voiced, the matching audio file plays spatially.
#
# BARK LINE FILE LOCATION:
#   dialogue/scripts/barks/{category}/{npc_id}.txt
#   Category folders: combat / exploration / reactive / idle / banter
#
# BARK LINE FILE FORMAT (matches design/BARK_LIBRARY.md):
#   # Trigger: COMBAT_ENGAGE
#   NPC_NAME: [determined] Three of them.
#   NPC_NAME: [serious tone] Stay close.
#
#   # Trigger: COMBAT_LOW_HP
#   NPC_NAME: [out of breath] I cannot hold much more.
#
# AUDIO FILE LOCATION (generated by TTS pipeline):
#   assets/audio/barks/{npc_id}/{trigger_id}_{variant_index}.ogg
#   Example: assets/audio/barks/tomlin/PLAYER_NEARBY_0.ogg

extends Node

# ── Configuration ─────────────────────────────────────────────────────────────

## How long the bark overlay stays on screen (seconds).
const DISPLAY_DURATION: float = 3.5

## The categories of bark files to scan on startup.
## Must match the subfolder names under dialogue/scripts/barks/.
const BARK_CATEGORIES: Array[String] = [
	"combat", "exploration", "reactive", "idle", "banter"
]

# ── Internal Storage ──────────────────────────────────────────────────────────

# Bark pools loaded from text files.
# Format: { "npc_id": { "TRIGGER_ID": ["line 1", "line 2", ...] } }
var _pools: Dictionary = {}

# Reference to the bark overlay UI node (set in _ready once UI scene is ready).
var _overlay: Control = null

# Tracks which line index was last used per NPC+trigger to avoid immediate repeats.
# Format: { "npc_id:TRIGGER_ID": last_index }
var _last_used: Dictionary = {}

# ── Lifecycle ─────────────────────────────────────────────────────────────────

func _ready() -> void:
	_load_all_bark_files()

# ── Public API ────────────────────────────────────────────────────────────────

## Called by NPC.fire_bark(). Picks a random line and shows it.
## npc_id must match NPCData.npc_id.
## trigger_id must match a trigger from design/BARK_LIBRARY.md.
## world_position is used to route 3D spatial audio to the right spot.
func fire(npc_id: String, trigger_id: String, world_position: Vector3) -> void:
	var line := _pick_line(npc_id, trigger_id)
	if line == "":
		return  # No lines registered for this NPC + trigger — silent.

	_show_overlay(npc_id, line)
	_play_audio(npc_id, trigger_id, world_position)

# ── Line Selection ────────────────────────────────────────────────────────────

func _pick_line(npc_id: String, trigger_id: String) -> String:
	if not _pools.has(npc_id):
		return ""
	if not _pools[npc_id].has(trigger_id):
		return ""

	var pool: Array = _pools[npc_id][trigger_id]
	if pool.is_empty():
		return ""

	# Pick randomly, but avoid repeating the last line used (if pool > 1).
	var key := npc_id + ":" + trigger_id
	var last: int = _last_used.get(key, -1)
	var index: int = randi() % pool.size()

	if pool.size() > 1:
		while index == last:
			index = randi() % pool.size()

	_last_used[key] = index
	return pool[index]

# ── Overlay Display ───────────────────────────────────────────────────────────

func _show_overlay(npc_id: String, line: String) -> void:
	# If the BarkOverlay UI node isn't connected yet, try to find it.
	if _overlay == null:
		_overlay = get_tree().get_first_node_in_group("bark_overlay")

	if _overlay == null:
		# Fallback: print to Output so barks are visible during development
		# even before the UI is built.
		print("[BARK] %s: %s" % [npc_id, line])
		return

	# The BarkOverlay node should have a show_bark(npc_id, line) method.
	if _overlay.has_method("show_bark"):
		_overlay.show_bark(npc_id, line, DISPLAY_DURATION)

# ── Audio Playback ────────────────────────────────────────────────────────────

func _play_audio(npc_id: String, trigger_id: String, world_position: Vector3) -> void:
	# Audio files follow the naming convention:
	#   assets/audio/barks/{npc_id}/{trigger_id}_{variant}.ogg
	# We try variant 0 through 4. The line picker already chose an index;
	# ideally we'd pass the index here. For now, play a matching file if it exists.
	var key := npc_id + ":" + trigger_id
	var variant: int = _last_used.get(key, 0)
	var audio_path := "res://assets/audio/barks/%s/%s_%d.ogg" % [npc_id, trigger_id, variant]

	if not ResourceLoader.exists(audio_path):
		return  # No audio yet — text overlay only (expected during early production).

	# Create a one-shot AudioStreamPlayer3D at the NPC's world position.
	var player := AudioStreamPlayer3D.new()
	get_tree().current_scene.add_child(player)
	player.stream = load(audio_path)
	player.global_position = world_position
	player.play()
	# Auto-free when done.
	player.finished.connect(player.queue_free)

# ── File Loading ──────────────────────────────────────────────────────────────

func _load_all_bark_files() -> void:
	var base_path := "res://dialogue/scripts/barks/"
	for category in BARK_CATEGORIES:
		var dir_path := base_path + category + "/"
		var dir := DirAccess.open(dir_path)
		if dir == null:
			continue  # Category folder doesn't exist yet — skip silently.
		dir.list_dir_begin()
		var filename := dir.get_next()
		while filename != "":
			if filename.ends_with(".txt"):
				var npc_id := filename.get_basename()
				_load_bark_file(dir_path + filename, npc_id)
			filename = dir.get_next()
		dir.list_dir_end()

func _load_bark_file(path: String, npc_id: String) -> void:
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		push_warning("BarkManager: could not open %s" % path)
		return

	if not _pools.has(npc_id):
		_pools[npc_id] = {}

	var current_trigger: String = ""

	while not file.eof_reached():
		var raw_line: String = file.get_line().strip_edges()

		# Skip blank lines.
		if raw_line == "":
			continue

		# Trigger header: "# Trigger: TRIGGER_ID"
		if raw_line.begins_with("# Trigger:"):
			current_trigger = raw_line.replace("# Trigger:", "").strip_edges()
			if not _pools[npc_id].has(current_trigger):
				_pools[npc_id][current_trigger] = []
			continue

		# Dialogue line: "NPC_NAME: [tag] spoken text"
		# Strip the speaker prefix and store only the spoken portion.
		if current_trigger != "" and ":" in raw_line:
			var colon_pos: int = raw_line.find(":")
			var spoken: String = raw_line.substr(colon_pos + 1).strip_edges()
			if spoken != "":
				_pools[npc_id][current_trigger].append(spoken)

	file.close()

# ── Debug ─────────────────────────────────────────────────────────────────────

## Prints all loaded bark pools to the Output panel.
## Call from the DebugOverlay or the GDScript REPL during development.
func debug_print_pools() -> void:
	for npc_id in _pools.keys():
		print("── %s ──" % npc_id)
		for trigger_id in _pools[npc_id].keys():
			print("  %s: %d lines" % [trigger_id, _pools[npc_id][trigger_id].size()])
